### ISSUE TITLE
LookupError: No executor by the name "threadpool" was found

### ISSUE THREAD

**Issue by alexonab** [viniciuschiele/flask-apscheduler#10]
This error occurs when running the latest advanced.py example.

```
$ python foo.py                               
Traceback (most recent call last):
  File "foo.py", line 41, in <module>
    scheduler.init_app(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 71, in init_app
    self.__load_config()
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 202, in __load_config
    self.__scheduler.configure(**options)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 595, in _configure
    executor = self._create_plugin_instance('executor', plugin, value)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 766, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No executor by the name "threadpool" was found
```

**Comment by alexonab** [comment]
I found apscheduler 2.1.1 was installed.  upgrading to 3.x resolved this.
