### ISSUE TITLE
AttributeError: module 'flask_apscheduler.scheduler' has no attribute 'task'

### ISSUE THREAD

**Issue by abstract-thinking** [viniciuschiele/flask-apscheduler#108]
Hi @viniciuschiele,

I can't get the timer to start. The scheduler decorator and the task seems to be an issue. 
Do you have an idea?

2019-05-01 22:40:16,386 ERROR: Exception on /robots.txt [HEAD] [in /home/markus/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/markus/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/markus/venv/lib/python3.5/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/markus/venv/lib/python3.5/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/home/markus/timing-observer/app/__init__.py", line 83, in load_tasks
    from app import tasks
  File "/home/markus/timing-observer/app/tasks.py", line 25, in <module>
    @scheduler.task('cron', id='gi', day='1', hour='2')
AttributeError: module 'flask_apscheduler.scheduler' has no attribute 'task'

Here the code:
https://github.com/abstract-thinking/timing-observer/blob/master/app/tasks.py

And the source where I was thinking to find the solution:
https://github.com/viniciuschiele/flask-apscheduler/blob/master/COMMON-ISSUES.md

Thanks in advance,
Markus

**Comment by viniciuschiele** [comment]
Hi,

Task is a property from the APScheduler class.

e.g:

```python
from flask_apscheduler import APScheduler
scheduler = APScheduler()

@scheduler.task()
def job1():
    pass
````

**Comment by abstract-thinking** [comment]
Thanks, I got it to run.
