### ISSUE TITLE
Exception is raised when job arguments contain objects

### ISSUE THREAD

**Issue by pe2mbs** [viniciuschiele/flask-apscheduler#111]
When objects are passed as arguments to a job then the uri's /scheduler/jobs.... raises an exception.

2019-07-10 07:47:02,474 - flask.app - ERROR - Exception on /scheduler/jobs/job1 [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python36\lib\site-packages\flask_apscheduler\scheduler.py", line 373, in decorated
    return view_func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\flask_apscheduler\api.py", line 69, in get_job
    return jsonify(job)
  File "C:\Python36\lib\site-packages\flask_apscheduler\json.py", line 23, in jsonify
    return flask.current_app.response_class(dumps(data, indent=indent), status=status, mimetype='application/json')
  File "C:\Python36\lib\site-packages\flask_apscheduler\json.py", line 16, in dumps
    return json.dumps(obj, indent=indent, cls=JSONEncoder)
  File "C:\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python36\lib\site-packages\flask_apscheduler\json.py", line 37, in default
    return super(JSONEncoder, self).default(obj)
  File "C:\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Flask' is not JSON serializable

The can simply solved by adding in the flask_scheduler.json.JSONEncoder before the return statement the following.

        if isinstance( obj, object ):
            return str( obj )

**Comment by viniciuschiele** [comment]
Hi,

Why would you receive a Flask object by parameter in a task function?
