### ISSUE TITLE
ModuleNotFoundError: No module named 'scheduler'

### ISSUE THREAD

**Issue by Kobe972** [viniciuschiele/flask-apscheduler#217]
```
from flask import *
import datetime
import json
from werkzeug.utils import secure_filename
import os
from flask_apscheduler import APScheduler
from flask_apscheduler.schedulers.background import BackgroundScheduler

app = Flask(__name__)
...
class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': 'scheduler:reset_statuses',
            'trigger': 'cron',
            'day': '*',
            'hour': '0',
            'minute': '32',
            'second': '0'
        }
    ]
    SCHEDULER_API_ENABLED = True
def reset_statuses():
...
if __name__ == "__main__":
    app.config.from_object(Config())
    scheduler = APScheduler()
    scheduler.init_app(app)
    scheduler.start()
    app.run(host="0.0.0.0",port=7002)
```
Error message:
```
root@iZ2vcer6gtjgqafrlyp9bnZ:~# root@iZ2vcer6gtjgqafrlyp9bnZ:~# python3 server.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/util.py", line 298, in ref_to_obj
    obj = __import__(modulename, fromlist=[rest])
ModuleNotFoundError: No module named 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 105, in <module>
    scheduler.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_apscheduler/scheduler.py", line 84, in init_app
    self._load_jobs()
  File "/usr/local/lib/python3.8/dist-packages/flask_apscheduler/scheduler.py", line 336, in _load_jobs
    self.add_job(**job)
  File "/usr/local/lib/python3.8/dist-packages/flask_apscheduler/scheduler.py", line 168, in add_job
    return self._scheduler.add_job(**job_def)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/schedulers/base.py", line 438, in add_job
    job = Job(self, **job_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/job.py", line 162, in _modify
    func = ref_to_obj(func)
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/util.py", line 300, in ref_to_obj
    raise LookupError('Error resolving reference %s: could not import module' % ref)
LookupError: Error resolving reference scheduler:reset_statuses: could not import module
```
If I use pip install scheduler to install scheduler, then another error occurs:
```
(kobe_anlaigg) D:\programming\python\kobe_anlaigg\Scripts>python server.py
Traceback (most recent call last):
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\apscheduler\util.py", line 304, in ref_to_obj
    obj = getattr(obj, name)
AttributeError: module 'scheduler' has no attribute 'reset_statuses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programming\python\kobe_anlaigg\Scripts\server.py", line 105, in <module>
    scheduler.init_app(app)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\flask_apscheduler\scheduler.py", line 84, in init_app
    self._load_jobs()
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\flask_apscheduler\scheduler.py", line 336, in _load_jobs
    self.add_job(**job)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\flask_apscheduler\scheduler.py", line 168, in add_job
    return self._scheduler.add_job(**job_def)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\apscheduler\schedulers\base.py", line 438, in add_job
    job = Job(self, **job_kwargs)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\apscheduler\job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\apscheduler\job.py", line 162, in _modify
    func = ref_to_obj(func)
  File "D:\programming\python\kobe_anlaigg\lib\site-packages\apscheduler\util.py", line 307, in ref_to_obj
    raise LookupError('Error resolving reference %s: error looking up object' % ref)
LookupError: Error resolving reference scheduler:reset_statuses: error looking up object
```
The version of flask_scheduler is 1.12.4. Python 3.11.

**Comment by viniciuschiele** [comment]
The `func` definition is probably wrong. It's meant to be `JOB_MODULE:JOB_FUNC_NAME`

**Comment by Shivappa** [comment]
You need to install `apscheduler` library as well to use `flask_apscheduler`.
Do `pip install apscheduler` and `flask_apscheduler` on new `virtual env` space and try again.

Also as @viniciuschiele pointed remove `scheduler` from `scheduler:reset_statuses` and try again.
