### ISSUE TITLE
KeyError: 'JSONIFY_PRETTYPRINT_REGULAR' when running Flask as a development server

### ISSUE THREAD

**Issue by chandrasekharan98** [viniciuschiele/flask-apscheduler#232]
While running Flask in a development server, I obtain this key error for `JSONIFY_PRETTYPRINT_REGULAR` when I try to hit the `GET /scheduler` endpoint. I had just started the scheduler and no jobs were added but I doubt if that's related to the issue here.
FYI I've enabled the REST API for the scheduler and I'm connecting to a postgres DB.

**Versions used**
```
APScheduler==3.10.4
flask==2.3.3
Flask-APScheduler==1.12.4
```

**Traceback**
```
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.103:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 132-532-373
127.0.0.1 - - [04/Sep/2023 19:48:07] "GET /scheduler HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask_apscheduler/scheduler.py", line 381, in decorated
    return view_func(*args, **kwargs)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask_apscheduler/api.py", line 34, in get_scheduler_info
    return jsonify(d)
  File "/home/chandru/scheduler/.venv/lib/python3.9/site-packages/flask_apscheduler/json.py", line 21, in jsonify
    if flask.current_app.config['JSONIFY_PRETTYPRINT_REGULAR']:
KeyError: 'JSONIFY_PRETTYPRINT_REGULAR'
```

PS: I suspect that its an issue related to [version 2.3.0 changes of Flask](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0) where they removed the key [JSONIFY_PRETTYPRINT_REGULAR](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0:~:text=JSONIFY_MIMETYPE%2C%20and-,JSONIFY_PRETTYPRINT_REGULAR,-config%20keys%20are). [This commit](https://github.com/viniciuschiele/flask-apscheduler/commit/ede0c264a4e2c06b6238238ff9b6e89e059ea14a) should fix it ideally however I seem to face the error in the latest release (`1.12.4`)

**Comment by viniciuschiele** [comment]
I will try to release a new version this week with the new commits.

**Comment by viniciuschiele** [comment]
[v1.13.0](https://github.com/viniciuschiele/flask-apscheduler/releases/tag/1.13.0) has been released
