### ISSUE TITLE
sudo apt install python3-flask-apscheduler WANTED

### ISSUE THREAD

**Issue by clemefr** [viniciuschiele/flask-apscheduler#250]
We need to install globally flask-APScheduler

flask-APScheduler is available from https://pypi.org/  (with sudo pip3 install)

The reason why the pip install command doesn’t work in Ubuntu >23.04 is down to an intentional shift in policy (also taken in Ubuntu’s upstream, Debian) to avoid conflicts between the Python package manager and Ubuntu’s underlying APT.
Basically, you can’t run pip install outside a virtual environment in Ubuntu 23.04. If you try to, you get a “externally managed environment” error

As many have already did (python3-flask-sqlalchemy, python3-flask-mail, etc.. ), python3-flask-apscheduler is still missing for installation with sudo apt install

**Comment by savchenko** [comment]
You still can use virtualenvs. `pipx`, `poetry`, etc. all work as usual.

**Comment by kmccurley** [comment]
The install doesn't even work under virtualenvs any more. 
```
python3 -m pip install flask_apscheduler
Collecting flask_apscheduler
  Using cached Flask-APScheduler-1.13.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info
      writing /tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-efn6ykm3/Flask_APScheduler.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s3ch0lfb/flask-apscheduler_7ca2105e8f34496c8b3755f9c498468f/setup.py", line 6, in <module>
          setup(
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 546, in run
          self.prune_file_list()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/command/sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/kevin/venv/publish/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
