### ISSUE TITLE
'Scheduler is already running' error with persistent job store

### ISSUE THREAD

**Issue by jdstone** [viniciuschiele/flask-apscheduler#252]
In the below configuration/setup, the job is not created in the persistent store, `job_scheduler.db`. If I remove `scheduler.start()` from `__init__.py` and add it to `extensions.py`, then the job is created in the persistent store. But in that configuration, when I run Flask, I receive an error that the scheduler is already running. The error is below. Why do I receive this error? How do I fix this? Any help would be appreciated. Thank you.

## `Error`

```
$ flask run
Pending jobs:
    mydatejob (trigger: date[2024-11-06 16:30:05 PST], pending)
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Jobstore default:
    mydatejob (trigger: date[2024-11-06 16:30:05 PST], next run at: 2024-11-06 16:30:05 PST)
Traceback (most recent call last):
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask/cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask/cli.py", line 262, in locate_app
    return find_best_app(module)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask/cli.py", line 72, in find_best_app
    app = app_factory()
          ^^^^^^^^^^^^^
  File "/home/jd/projects/flight-check-in-flask/app/__init__.py", line 34, in create_app
    scheduler.init_app(app)
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask_apscheduler/scheduler.py", line 82, in init_app
    self._load_config()
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/flask_apscheduler/scheduler.py", line 288, in _load_config
    self._scheduler.configure(**options)
  File "/home/jd/projects/flight-check-in-flask/lib/python3.12/site-packages/apscheduler/schedulers/base.py", line 118, in configure
    raise SchedulerAlreadyRunningError
apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running
 * Debugger is active!
 * Debugger PIN: 632-718-895
```

## `app/__init__.py`

```python
from app.extensions import scheduler
from config import config
from flask import Flask
import os


def create_app(config_class=os.getenv('FLASK_ENV') or 'default'):
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(config[config_class])

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    ###################################################
    #### Register Blueprints
    ###################################################    
    from . import checkin
    app.register_blueprint(checkin.bp)

    ###################################################
    #### Initialize Extensions
    ###################################################
    scheduler.init_app(app)
    scheduler.start()

    return app
```

## `app/extensions.py`

```python
from flask_apscheduler import APScheduler
from flask_apscheduler.scheduler import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore


jobstores = {
    'default': SQLAlchemyJobStore(url='sqlite:///job_scheduler.db')
}

###################################################
#### Initialize APScheduler
###################################################
scheduler = APScheduler(BackgroundScheduler(jobstores=jobstores))
```

## `app/checkin.py`

```python
from app import scheduler
from datetime import datetime
from flask import Blueprint


bp = Blueprint('checkin', __name__, url_prefix='/')

def my_job():
    print('this is my job')


scheduler.add_job('mydatejob', my_job, run_date=datetime(2024, 11, 6, 16, 30, 5))

scheduler.scheduler.print_jobs()
```

**Comment by jdstone** [comment]
I got this fixed. I believe what fixed it was wrapping the `scheduler.start()` call in a try/except block in `__init__.py`.

```
try:
        scheduler.start() # APScheduler WORKS-kinda
    except (KeyboardInterrupt, SystemExit):
        pass
```

**Comment by jdstone** [comment]
Now it's not working working again! I haven't really changed my code. It's not using the SQLite job_store that I've specified. The `job_scheduler.db` file never gets created, but the job I add (my_job1) looks like it is indeed created because the `print_jobs()` method prints them.

Here's how my code looks now, which isn't much different.

## `__init__.py`

```
from app.extensions import scheduler
from config import config
from flask import Flask
import os


def create_app(config_class=os.getenv('FLASK_ENV') or 'default'):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(config[config_class])

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    ###################################################
    #### Register Blueprints
    ###################################################
    from . import checkin
    app.register_blueprint(checkin.bp)

    ###################################################
    #### Initialize Extensions
    ###################################################
    scheduler.init_app(app)
    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        pass

    return app
```

## `extensions.py`

```
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from flask_apscheduler import APScheduler
from flask_apscheduler.scheduler import BackgroundScheduler


jobstores = {
    'default': SQLAlchemyJobStore(url='sqlite:///job_scheduler.db')
}

###################################################
#### Initialize APScheduler
###################################################
scheduler = APScheduler(BackgroundScheduler(jobstores=jobstores))
```

## `checkin.py`

```
from app import scheduler
from datetime import datetime, timedelta
from flask import Blueprint, jsonify
import logging


bp = Blueprint('checkin', __name__, url_prefix='/')

def my_job():
    print('this is my job')

if not scheduler.get_job('my_job1'):
    scheduler.add_job(id='my_job1', func=my_job, trigger="date", run_date=datetime(2024, 11, 29, 15, 50, 0))

scheduler.scheduler.print_jobs()
```
