### ISSUE TITLE
Value Error when running jobs.py

### ISSUE THREAD

**Issue by matteobagheri** [viniciuschiele/flask-apscheduler#33]
When I run the example jobs.py in the python shell, I get this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/FlaskApp/varie/scheduler_example.py", line 21, in <module>
    scheduler.init_app(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 68, in init_app
    self._load_jobs()
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 269, in _load_jobs
    self.add_job(**job)
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 129, in add_job
    return self._scheduler.add_job(**job_def)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 425, in add_job
    job = Job(self, **job_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/job.py", line 44, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/job.py", line 157, in _modify
    func = ref_to_obj(func)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/util.py", line 270, in ref_to_obj
    raise LookupError('Error resolving reference %s: could not import module' % ref)
LookupError: Error resolving reference jobs:job1: could not import module

I didn't do any modification to the code. What am I doing wrong?

Thanks in advance.

**Comment by matteobagheri** [comment]
I renamed the script, dumb me. At line 9 ("'func': 'jobs:job1'"), jobs refers to the name of the script.
