### ISSUE TITLE
exception when call delete_all_jobs method

### ISSUE THREAD

**Issue by beshe** [viniciuschiele/flask-apscheduler#53]
Hi Vinicius,

I'd tried to use it in my project, and  encounter exception when call  the delete_all_jobs method , but it works when call the delete_job separately, below is the source and exception,Can you give some advise?

```
@schedule.route('/delete/<name>')
def deletejob(name):
    logger.info('Delete the schedule job for %s' %name)
    scheduler.delete_job(name)
    return redirect(url_for('schedule.joblist'))


@schedule.route('/deleteall')
def deleteall():
    scheduler.delete_all_jobs()
    logger.info("Delete all of the cronjob")
    flash('all jobs removed')
    return redirect(url_for('schedule.joblist'))
```

**Exception:**
```
TypeError
TypeError: _remove() takes at least 2 arguments (1 given)
```

**Comment by viniciuschiele** [comment]
Hi @beshe,

Are you using a persisted job store (like SQLALchemy, MongoDB) or the default one (in memory)?

I'm asking it because the delete_all_jobs with in memory job store doesn't call any ```_remove()```.

Can you see the stack trace for this error?

**Comment by beshe** [comment]
yes, I'm using the MongoDB as the jobstore.

```
    SCHEDULER_JOBSTORES = {
        'default': MongoDBJobStore(host='localhost', port=27017)
    }
    SCHEDULER_API_ENABLE = True
    SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 3
    }
```
below is the trace log.

```
Traceback (most recent call last)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask_debugtoolbar\__init__.py", line 125, in dispatch_request
return view_func(**req.view_args)
File "D:\workspace\FlaskProject\flask_study\StockProject\app\schedule\views.py", line 121, in deleteall
scheduler.delete_all_jobs()
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\flask_apscheduler\scheduler.py", line 164, in delete_all_jobs
self._scheduler.remove_all_jobs(jobstore)
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\apscheduler\schedulers\base.py", line 638, in remove_all_jobs
store.remove_all_jobs()
File "D:\workspace\Python\VirtualEnvs\stock\lib\site-packages\apscheduler\jobstores\mongodb.py", line 109, in remove_all_jobs
self.collection.remove()
TypeError: _remove() takes at least 2 arguments (1 given)
```

**Comment by viniciuschiele** [comment]
Yeah, it seems to be related to the MongoDB job store, what version of ```pymongo``` are you using?

**Comment by beshe** [comment]
here is the version in my local environment.  Strange, I've tried python2.7.12 and python3.6, both not work, I need to do further research.

MongoDB version is v3.4.2

```
APScheduler==3.3.1
Flask==0.12.2
Flask-APScheduler==1.7.0
mongoengine==0.13.0
pymongo==3.5.0
```

**Comment by viniciuschiele** [comment]
Feel free to reopen it again if you need it.
