### ISSUE TITLE
How do you correctly delete the SCHEDULER_JOBSTORES database?

### ISSUE THREAD

**Issue by spitfiredd** [viniciuschiele/flask-apscheduler#54]
So, I am messing about running the advanced example. I copy over the config to a `config.py` file. Next, when I run the example again I get the error below.  Next, I just switch over to my database and delete the `apscheduler_jobs` table from my database, then when I run the example again I get the same error. I have tried changing the id to a new id but that doesn't work either.

What is the correct way to remove the apscheduler_jobs table from my database while I am testing and making mistakes?

```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 92, in add_job
    self.engine.execute(insert)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 2055, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "apscheduler_jobs_pkey"
DETAIL:  Key (id)=(job1) already exists.
 [SQL: 'INSERT INTO apscheduler_jobs (id, next_run_time, job_state) VALUES (%(id)s, %(next_run_time)s, %(job_state)s)'] [parameters: {'id': 'job1', 'next_run_time': 1504900413.448354, 'job_state': <psycopg2.extensions.Binary object at 0x00000192D8EBD238>}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 53, in <module>
    scheduler.start()
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\flask_apscheduler\scheduler.py", line 82, in start
    self._scheduler.start()
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\base.py", line 154, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\base.py", line 851, in _real_add_job
    store.add_job(job)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 94, in add_job
    raise ConflictingIdError(job.id)
apscheduler.jobstores.base.ConflictingIdError: 'Job identifier (job1) conflicts with an existing job'
```

**Comment by viniciuschiele** [comment]
Hi,

If you have your tasks in the config.py and you are using a persisted job store (sqlalchemy, mongodb...), every time you run your app Flask-APScheduler will try to add again those jobs to the job store and it will raise an error because the jobs already exist there.

**Comment by spitfiredd** [comment]
Should I keep the config for Flask-APScheduler in the file I create my app in?

**Comment by viniciuschiele** [comment]
Hi,

If you want to keep your jobs in the config file you can use [replace_existing: True](http://apscheduler.readthedocs.io/en/latest/userguide.html), it will override the jobs in the job store every time your app runs.

If you don't want this behavior you can't keep the jobs in the config file.

**Comment by spitfiredd** [comment]
Well, maybe my issue is not with the jobs but with the Jobstore?? Because now I am running into errors when I try your examples. For example, either `advanced.py` or `flask_context.py` give me the error,

```
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    scheduler.start()
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\flask_apscheduler\scheduler.py", line 82, in start
    self._scheduler.start()
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\base.py", line 154, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\schedulers\base.py", line 851, in _real_add_job
    store.add_job(job)
  File "C:\Anaconda3\envs\g2x_flask\lib\site-packages\apscheduler\jobstores\sqlalchemy.py", line 94, in add_job
    raise ConflictingIdError(job.id)
apscheduler.jobstores.base.ConflictingIdError: 'Job identifier (job1) conflicts with an existing job'
```

It works the first time it runs, but then when I run the script again that is when I get the error, with `advanced.py` this happens when I change from `url='sqlite://'` to something persistant, ie `url='sqlite://.test.db'`

Is there something I am doing wrong running your examples?

Also, I am not even sure if this is an issue with your package since the errors seem to be coming from apscheduler and not flask-apscheduler?

**Comment by viniciuschiele** [comment]
It doesn't work, you can't put your jobs in the config file and use a persisted job store because every time you run your app it will try to add your jobs in the job store.

An alternative would be using ```replace_existing: True```

**Comment by spitfiredd** [comment]
I see. Where does the `replace_existing: True` go?  Also, what is the point of having a job a database? Is it even required?

**Comment by viniciuschiele** [comment]
For example, if you have a job to run every hour and the next trigger is 14:00, for some reason you had to stop and start your app 5 minutes before (like 13:55), the next trigger is going be 14:55 and not 14:00 as before. It may be an issue in some scenarios.

**Comment by viniciuschiele** [comment]
Feel free to reopen it again if you need it.
