### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: u'Can not find timezone China Standard time'

### ISSUE THREAD

**Issue by zhuxiangyi** [viniciuschiele/flask-apscheduler#77]
Traceback (most recent call last):
  File "D:/code/hadoo_client_deploy/app.py", line 63, in <module>
    scheduler.init_app(app)
  File "C:\Python27\lib\site-packages\flask_apscheduler\scheduler.py", line 77, in init_app
    self._load_config()
  File "C:\Python27\lib\site-packages\flask_apscheduler\scheduler.py", line 304, in _load_config
    self._scheduler.configure(**options)
  File "C:\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 122, in configure
    self._configure(config)
  File "C:\Python27\lib\site-packages\apscheduler\schedulers\background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "C:\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 691, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "C:\Python27\lib\site-packages\tzlocal\win32.py", line 87, in get_localzone
    _cache_tz = pytz.timezone(get_localzone_name())
  File "C:\Python27\lib\site-packages\tzlocal\win32.py", line 80, in get_localzone_name
    raise pytz.UnknownTimeZoneError('Can not find timezone ' + tzkeyname)
pytz.exceptions.UnknownTimeZoneError: u'Can not find timezone China Standard time'

**Comment by viniciuschiele** [comment]
Hi,

Looks like pytz does not support the timezone (China Standard Time) that your operating system has provided, I have never seen that happening before though.

You can see all time zones supported by pytz running this code.

```python
import pytz

for tz in pytz.all_timezones:
    print tz
```

Sorry, I can't help much on it.
