### ISSUE TITLE
Working outside of application context.

### ISSUE THREAD

**Issue by callmeJoey** [viniciuschiele/flask-apscheduler#85]
File "E:\xcode\apst\apst\model\db\app_db.py", line 9, in __init__
    db_uri = current_app.config['APP_DB_URI']
  File "e:\xcode\apst\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "e:\xcode\apst\venv\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "e:\xcode\apst\venv\lib\site-packages\flask\globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

can you help me how to fixed?

you know your example's jobs are all define in the same py file, once you put the job function in another file that need to access current_app, got above error.

thanks

**Comment by viniciuschiele** [comment]
Hi,

Sorry for the delay

You need to use the original **app** instance to create a flask context.

The solution depends on how you are organizing your project, I would suggest you to get the flask instance from the **scheduler**.

Below an example, I'm assuming you have a method to create the Flask app (that's why I think you are using the **current_app**)

e.g:

_init_.py
```python
scheduler = APScheduler()
```
application.py
```python
from . import scheduler

def create_app():
    app = Flask()
    scheduler.init_app(app)
    return app
```

jobs.py
```python
from . import scheduler

def job1():
    with scheduler.app.app_context():
        # your magic here :)
```

I hope that helps.

**Comment by callmeJoey** [comment]
Hi,

so amazing, `with scheduler.app.app_context():` it works for me. thanks a lot. this problem has been bothering me for a long time. 👍 💯

thanks.

**Comment by caio-vinicius** [comment]
I was using request.post, request.put instead of request**s**.post, request**s**.put.

**Comment by kirantpatil** [comment]
I am having same issue with my below code. Please help me to resolve the issue. All of it is in the same file of flask app.

### Runtime error
```
>> flask run -h 0.0.0.0
>>
 * Serving Flask app "ka_web.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 185-670-687
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Job "job_pullKa (trigger: cron[hour='18', minute='31'], next run at: 2022-04-21 18:31:00 IST)" raised an 
exception
Traceback (most recent call last):
  File "c:\users\x0120370\appdata\local\programs\python\python39\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\my_docs\code\python\production\ka-service\ka_web.py", line 99, in job_pullKa
    return pullKa_new()
  File "C:\my_docs\code\python\production\ka-service\ka_web.py", line 77, in pullKa_new
    if 'ka_lookup_days' in request.args:
  File "c:\users\x0120370\appdata\local\programs\python\python39\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\x0120370\appdata\local\programs\python\python39\lib\site-packages\werkzeug\local.py", line 307, in _get_current_object
    return self.__local()
  File "c:\users\x0120370\appdata\local\programs\python\python39\lib\site-packages\flask\globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```


### Source code:

```
SCHEDULE_HOUR = int(os.environ.get('SCHEDULE_HOUR'))
SCHEDULE_MINUTE = int(os.environ.get('SCHEDULE_MINUTE'))

app = Flask(__name__)
app.config.from_object(Config())
scheduler = APScheduler()
scheduler.init_app(app)
scheduler.start()

@scheduler.task('cron', id='do_pullka', hour=SCHEDULE_HOUR, minute=SCHEDULE_MINUTE)
def job_pullKa():
    with scheduler.app.app_context():
        return pullKa_new()
```

**Comment by christopherpickering** [comment]
What is in your `pullKa_new()` function? You probably need `with scheduler.app.app_context():` inside the function you are calling.

**Comment by kirantpatil** [comment]
@christopherpickering, I have added inside the function as below and still shows same error

```
def pullKa_new():
    with scheduler.app.app_context():
        now = datetime.now()
        if request:
            logger.info("pullKa() Invoked by " + str(request.jwt_decoded))

        if 'ka_lookup_days' in request.args:
            ka_lookup_days = request.args.get("ka_lookup_days")
            try:
                ka_lookup_days = int(ka_lookup_days)

                if ka_lookup_days < 0:
                    return response_message("KA_LOOKUP_DAYS should be greater than 0", 400)
                    
            except ValueError:
                return response_message("KA_LOOKUP_DAYS should be integer", 400)
        else:
            ka_lookup_days = 0

        logger.info("pullka() Invoked at" + str(now))
        sys.stdout.flush()
        pull_data(ka_lookup_days)  # implement a fully native python scheduler
        return "Pulled!"
```
